version: '3.3'
services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_reto_devops
    volumes:
      - ./reverse_proxy/nginx.conf;/etc/nginx/nginx.conf
    ports:
      - 80:80